import { TicketRecord } from "./types";

export const INITIAL_MOCK_DATA: TicketRecord[] = [
  {
    "Nombre de Cuenta": "Acme Corp",
    "Clasificaciones": "Socio Oro",
    "Propietario de Ticket": "Soporte Nivel 2",
    "ID de Ticket": "TKT-10401",
    "Asunto": "Fallo crítico en base de datos PostgreSQL de producción",
    "Categoria (Ticket)": "Base de Datos",
    "Prioridad (Ticket)": "Crítica",
    "Estado (Ticket)": "Abierto",
    "Hora de creación (Ticket)": "2026-06-25 05:30:00",
    "Ticket Tiempo terminado": "",
    "Tiempo total empleado": "0",
    "Ingeniero de soporte asignado": "Carlos Ruiz",
    "Tipo de vulneración del SLA": "Tiempo de Respuesta Excedido",
    "Tiempo de respuesta del agente": "",
    "Tiempo de primera respuesta en horario laboral": "320", // 320 minutes delayed
    "Tiempo total de respuesta en horario laboral": "",
    "Número de respuestas": "0",
    "Hora de responder": ""
  },
  {
    "Nombre de Cuenta": "Global Finance Inc.",
    "Clasificaciones": "Socio Oro",
    "Propietario de Ticket": "Soporte Nivel 3",
    "ID de Ticket": "TKT-10402",
    "Asunto": "Lentitud extrema en pasarela de pagos transaccionales",
    "Categoria (Ticket)": "Servidores",
    "Prioridad (Ticket)": "Crítica",
    "Estado (Ticket)": "En Progreso",
    "Hora de creación (Ticket)": "2026-06-25 06:10:00",
    "Ticket Tiempo terminado": "",
    "Tiempo total empleado": "2.5",
    "Ingeniero de soporte asignado": "Sofía López",
    "Tipo de vulneración del SLA": "Ninguna",
    "Tiempo de respuesta del agente": "15",
    "Tiempo de primera respuesta en horario laboral": "480", // 480 minutes delayed (very high)
    "Tiempo total de respuesta en horario laboral": "480",
    "Número de respuestas": "1",
    "Hora de responder": "2026-06-25 06:25:00"
  },
  {
    "Nombre de Cuenta": "Tech Solutions",
    "Clasificaciones": "Socio Plata",
    "Propietario de Ticket": "Soporte Nivel 1",
    "ID de Ticket": "TKT-10403",
    "Asunto": "Error de sincronización con API de inventarios externa",
    "Categoria (Ticket)": "Software",
    "Prioridad (Ticket)": "Alta",
    "Estado (Ticket)": "Abierto",
    "Hora de creación (Ticket)": "2026-06-24 14:00:00",
    "Ticket Tiempo terminado": "",
    "Tiempo total empleado": "0",
    "Ingeniero de soporte asignado": "Ana Gómez",
    "Tipo de vulneración del SLA": "Tiempo de Respuesta Excedido",
    "Tiempo de respuesta del agente": "",
    "Tiempo de primera respuesta en horario laboral": "210", // 210 minutes
    "Tiempo total de respuesta en horario laboral": "",
    "Número de respuestas": "0",
    "Hora de responder": ""
  },
  {
    "Nombre de Cuenta": "Apex Retail",
    "Clasificaciones": "Cliente Estándar",
    "Propietario de Ticket": "Soporte Nivel 1",
    "ID de Ticket": "TKT-10404",
    "Asunto": "Terminales punto de venta (POS) sin conexión",
    "Categoria (Ticket)": "Redes",
    "Prioridad (Ticket)": "Alta",
    "Estado (Ticket)": "Abierto",
    "Hora de creación (Ticket)": "2026-06-25 08:00:00",
    "Ticket Tiempo terminado": "",
    "Tiempo total empleado": "0.5",
    "Ingeniero de soporte asignado": "Luis Martínez",
    "Tipo de vulneración del SLA": "Ninguna",
    "Tiempo de respuesta del agente": "25",
    "Tiempo de primera respuesta en horario laboral": "25",
    "Tiempo total de respuesta en horario laboral": "25",
    "Número de respuestas": "1",
    "Hora de responder": "2026-06-25 08:25:00"
  },
  {
    "Nombre de Cuenta": "Starlight Industries",
    "Clasificaciones": "Socio Oro",
    "Propietario de Ticket": "Soporte Nivel 2",
    "ID de Ticket": "TKT-10405",
    "Asunto": "Solicitud de aumento de almacenamiento en la nube AWS",
    "Categoria (Ticket)": "Servidores",
    "Prioridad (Ticket)": "Media",
    "Estado (Ticket)": "Pendiente",
    "Hora de creación (Ticket)": "2026-06-24 11:30:00",
    "Ticket Tiempo terminado": "",
    "Tiempo total empleado": "1.2",
    "Ingeniero de soporte asignado": "Carlos Ruiz",
    "Tipo de vulneración del SLA": "Ninguna",
    "Tiempo de respuesta del agente": "45",
    "Tiempo de primera respuesta en horario laboral": "45",
    "Tiempo total de respuesta en horario laboral": "45",
    "Número de respuestas": "2",
    "Hora de responder": "2026-06-24 12:15:00"
  },
  {
    "Nombre de Cuenta": "Novatech Labs",
    "Clasificaciones": "Socio Plata",
    "Propietario de Ticket": "Soporte Nivel 2",
    "ID de Ticket": "TKT-10406",
    "Asunto": "VPN corporativa caída para la oficina de sucursal norte",
    "Categoria (Ticket)": "Redes",
    "Prioridad (Ticket)": "Alta",
    "Estado (Ticket)": "Abierto",
    "Hora de creación (Ticket)": "2026-06-25 04:15:00",
    "Ticket Tiempo terminado": "",
    "Tiempo total empleado": "0",
    "Ingeniero de soporte asignado": "Ana Gómez",
    "Tipo de vulneración del SLA": "Tiempo de Respuesta Excedido",
    "Tiempo de respuesta del agente": "",
    "Tiempo de primera respuesta en horario laboral": "180", // 180 minutes delayed
    "Tiempo total de respuesta en horario laboral": "",
    "Número de respuestas": "0",
    "Hora de responder": ""
  },
  {
    "Nombre de Cuenta": "Innova Health",
    "Clasificaciones": "Socio Oro",
    "Propietario de Ticket": "Soporte Nivel 3",
    "ID de Ticket": "TKT-10407",
    "Asunto": "Fuga de datos reportada en el portal de pacientes",
    "Categoria (Ticket)": "Seguridad",
    "Prioridad (Ticket)": "Crítica",
    "Estado (Ticket)": "Abierto",
    "Hora de creación (Ticket)": "2026-06-25 07:45:00",
    "Ticket Tiempo terminado": "",
    "Tiempo total empleado": "0",
    "Ingeniero de soporte asignado": "Sofía López",
    "Tipo de vulneración del SLA": "Ninguna",
    "Tiempo de respuesta del agente": "",
    "Tiempo de primera respuesta en horario laboral": "15", // 15 minutes delayed
    "Tiempo total de respuesta en horario laboral": "",
    "Número de respuestas": "0",
    "Hora de responder": ""
  },
  {
    "Nombre de Cuenta": "Acme Corp",
    "Clasificaciones": "Socio Oro",
    "Propietario de Ticket": "Soporte Nivel 1",
    "ID de Ticket": "TKT-10408",
    "Asunto": "Error en login tras reset de contraseña masivo",
    "Categoria (Ticket)": "Software",
    "Prioridad (Ticket)": "Media",
    "Estado (Ticket)": "Cerrado",
    "Hora de creación (Ticket)": "2026-06-24 09:15:00",
    "Ticket Tiempo terminado": "2026-06-24 13:45:00",
    "Tiempo total empleado": "4.5",
    "Ingeniero de soporte asignado": "Luis Martínez",
    "Tipo de vulneración del SLA": "Ninguna",
    "Tiempo de respuesta del agente": "30",
    "Tiempo de primera respuesta en horario laboral": "30",
    "Tiempo total de respuesta en horario laboral": "120",
    "Número de respuestas": "3",
    "Hora de responder": "2026-06-24 09:45:00"
  },
  {
    "Nombre de Cuenta": "Apex Retail",
    "Clasificaciones": "Cliente Estándar",
    "Propietario de Ticket": "Soporte Nivel 1",
    "ID de Ticket": "TKT-10409",
    "Asunto": "Impresora de tickets no responde en caja 3",
    "Categoria (Ticket)": "Hardware",
    "Prioridad (Ticket)": "Baja",
    "Estado (Ticket)": "Cerrado",
    "Hora de creación (Ticket)": "2026-06-23 10:00:00",
    "Ticket Tiempo terminado": "2026-06-23 16:30:00",
    "Tiempo total empleado": "6.5",
    "Ingeniero de soporte asignado": "Carlos Ruiz",
    "Tipo de vulneración del SLA": "Ninguna",
    "Tiempo de respuesta del agente": "120",
    "Tiempo de primera respuesta en horario laboral": "120",
    "Tiempo total de respuesta en horario laboral": "240",
    "Número de respuestas": "2",
    "Hora de responder": "2026-06-23 12:00:00"
  },
  {
    "Nombre de Cuenta": "Tech Solutions",
    "Clasificaciones": "Socio Plata",
    "Propietario de Ticket": "Soporte Nivel 2",
    "ID de Ticket": "TKT-10410",
    "Asunto": "Fallo de conexión VPN IPsec sitio a sitio",
    "Categoria (Ticket)": "Redes",
    "Prioridad (Ticket)": "Alta",
    "Estado (Ticket)": "Abierto",
    "Hora de creación (Ticket)": "2026-06-24 17:30:00",
    "Ticket Tiempo terminado": "",
    "Tiempo total empleado": "0",
    "Ingeniero de soporte asignado": "Raúl Peña",
    "Tipo de vulneración del SLA": "Tiempo de Respuesta Excedido",
    "Tiempo de respuesta del agente": "",
    "Tiempo de primera respuesta en horario laboral": "540", // 540 minutes delayed (very high)
    "Tiempo total de respuesta en horario laboral": "",
    "Número de respuestas": "0",
    "Hora de responder": ""
  },
  {
    "Nombre de Cuenta": "Global Finance Inc.",
    "Clasificaciones": "Socio Oro",
    "Propietario de Ticket": "Soporte Nivel 3",
    "ID de Ticket": "TKT-10411",
    "Asunto": "Auditoría de Logs de Acceso de Administrador",
    "Categoria (Ticket)": "Seguridad",
    "Prioridad (Ticket)": "Media",
    "Estado (Ticket)": "Abierto",
    "Hora de creación (Ticket)": "2026-06-25 01:20:00",
    "Ticket Tiempo terminado": "",
    "Tiempo total empleado": "0",
    "Ingeniero de soporte asignado": "Sofía López",
    "Tipo de vulneración del SLA": "Ninguna",
    "Tiempo de respuesta del agente": "",
    "Tiempo de primera respuesta en horario laboral": "60",
    "Tiempo total de respuesta en horario laboral": "",
    "Número de respuestas": "0",
    "Hora de responder": ""
  },
  {
    "Nombre de Cuenta": "Innova Health",
    "Clasificaciones": "Socio Oro",
    "Propietario de Ticket": "Admin Soporte",
    "ID de Ticket": "TKT-10412",
    "Asunto": "Revisión mensual de disponibilidad de servidores",
    "Categoria (Ticket)": "Servidores",
    "Prioridad (Ticket)": "Baja",
    "Estado (Ticket)": "En Progreso",
    "Hora de creación (Ticket)": "2026-06-25 09:00:00",
    "Ticket Tiempo terminado": "",
    "Tiempo total empleado": "1.0",
    "Ingeniero de soporte asignado": "Raúl Peña",
    "Tipo de vulneración del SLA": "Ninguna",
    "Tiempo de respuesta del agente": "10",
    "Tiempo de primera respuesta en horario laboral": "10",
    "Tiempo total de respuesta en horario laboral": "10",
    "Número de respuestas": "1",
    "Hora de responder": "2026-06-25 09:10:00"
  },
  {
    "Nombre de Cuenta": "Acme Corp",
    "Clasificaciones": "Socio Oro",
    "Propietario de Ticket": "Admin Soporte",
    "ID de Ticket": "TKT-10413",
    "Asunto": "Actualización crítica de firmware del Switch core",
    "Categoria (Ticket)": "Redes",
    "Prioridad (Ticket)": "Crítica",
    "Estado (Ticket)": "Abierto",
    "Hora de creación (Ticket)": "2026-06-25 02:00:00",
    "Ticket Tiempo terminado": "",
    "Tiempo total empleado": "0",
    "Ingeniero de soporte asignado": "Sofía López",
    "Tipo de vulneración del SLA": "Tiempo de Respuesta Excedido",
    "Tiempo de respuesta del agente": "",
    "Tiempo de primera respuesta en horario laboral": "380", // 380 minutes delayed
    "Tiempo total de respuesta en horario laboral": "",
    "Número de respuestas": "0",
    "Hora de responder": ""
  },
  {
    "Nombre de Cuenta": "Starlight Industries",
    "Clasificaciones": "Socio Oro",
    "Propietario de Ticket": "Soporte Nivel 3",
    "ID de Ticket": "TKT-10414",
    "Asunto": "Incompatibilidad de librería de cifrado tras parche corporativo",
    "Categoria (Ticket)": "Software",
    "Prioridad (Ticket)": "Alta",
    "Estado (Ticket)": "Cerrado",
    "Hora de creación (Ticket)": "2026-06-23 15:30:00",
    "Ticket Tiempo terminado": "2026-06-24 10:30:00",
    "Tiempo total empleado": "19.0",
    "Ingeniero de soporte asignado": "Ana Gómez",
    "Tipo de vulneración del SLA": "Ninguna",
    "Tiempo de respuesta del agente": "30",
    "Tiempo de primera respuesta en horario laboral": "30",
    "Tiempo total de respuesta en horario laboral": "180",
    "Número de respuestas": "4",
    "Hora de responder": "2026-06-23 16:00:00"
  }
];
